# Generated by Django 5.2.1 on 2025-05-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('total_cores', models.IntegerField()),
                ('total_threads', models.IntegerField()),
                ('ram_total', models.FloatField()),
                ('ram_used', models.FloatField()),
                ('ram_available', models.FloatField()),
                ('storage_total', models.FloatField()),
                ('storage_used', models.FloatField()),
                ('storage_free', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ppid', models.IntegerField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.processdetail')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='base.systemdetail')),
            ],
        ),
    ]
